<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$_33bf = [
    "",
    "getDate",
    "getMonth",
    "getFullYear",
    "false",
    "R",
    "0",
    "1",
    "l",
    "roulettesound",
    "getElementById",
    "play",
    "pause",
    "value",
    "display",
    "style",
    "divhigh",
    "none",
    "divlow",
    "block",
    "resdiv",
    "qtyamt",
    "disabled",
    "btnadv",
    "advpan",
    "gamepan",
    "/",
    "onreadystatechange",
    "readyState",
    "status",
    "responseText",
    "!",
    "split",
    "innerHTML",
    "lastdraw",
    "innerText",
    "lastdrawr",
    "nextdraw",
    "spannews",
    "currdate",
    ",",
    "res0",
    "res1",
    "res2",
    "res3",
    "res4",
    "res5",
    "res6",
    "res7",
    "res8",
    "res9",
    "rres0",
    "rres1",
    "rres2",
    "rres3",
    "rres4",
    "rres5",
    "rres6",
    "rres7",
    "rres8",
    "rres9",
    "H7",
    "true",
    "creditlimit",
    "agentdet",
    "   WELCOME ",
    " (",
    ")",
    "msg",
    "Draw Over",
    "location",
    "index.asp",
    "GET",
    "game1param.asp",
    "open",
    "Content-type",
    "application/x-www-form-urlencoded",
    "setRequestHeader",
    "send",
    "src",
    "mul1",
    "images/1.png",
    "mul5",
    "images/5.png",
    "mul10",
    "images/10.png",
    "mul50",
    "images/50.png",
    "mul100",
    "images/100.png",
    "mul500",
    "images/500.png",
    "mul",
    "images/g",
    ".png",
    "width",
    "50",
    "height",
    "60",
    "@",
    "~",
    "Points:",
    "lasttsn",
    "POST",
    "game_proc.asp",
    "saleamt=",
    "&seriesa=",
    "&multiplier=",
    "&alltxta=",
    "&alltxtb=",
    "&alltxtc=",
    "&alltxtd=",
    "&alltxte=",
    "&alltxtf=",
    "&alltxtg=",
    "&alltxth=",
    "&alltxti=",
    "&alltxtj=",
    "&draw=",
    "&gmcd=",
    "&mrp=",
    "Please Login To Play..",
    "Are You Sure..!",
    "cancel_proc.asp",
    "passtsn=",
    "<table id='myTable'><tr><th>Draw Time</th><th>Sale Points</th><th>Cancel Points</th><th>Win Points</th></tr>",
    "OK",
    "length",
    "<tr><td><a onclick=funclastbet2('",
    "$",
    "')>",
    "</a></td><td>",
    "</td><td>",
    "</td></tr>",
    "<tr><td colspan='7'>Data Not Found....</td></tr>",
    "</table>",
    "betspan",
    "drawsale_proc.asp",
    "gmcd=",
    "<table id='myTable'><tr><th>TSN</th><th>Bet Time</th><th>Draw Time</th><th>Points</th><th>Cancel</th><th>Winning</th><th>Win Points</th></tr>",
    "<tr><td><a onclick=funclastbet3('",
    "lasttsn_proc.asp",
    "passstr=",
    "<table id='myTable'><tr><th>TSN</th><th>Schme Name</th><th>Num.</th><th>Qty.</th><th>Amt.</th></tr>",
    "Y",
    "<tr><td>",
    "</td><td bgcolor='green'><font color='white'>",
    "</font></td><td>",
    "tsndet_proc.asp",
    "&tsn=",
    "<table id='myTable'><tr><th>TSN</th><th>Bet Time</th><th>Draw Time</th><th>Points</th></tr>",
    "<tr><td><a onclick=funccancel('",
    "cantsn_proc.asp",
    "<table id='myTable1'><th>Draw Time</th><th class='sch1'>Golden 60A</th><th class='sch2'>Golden 61B</th><th class='sch3'>Golden 62C</th><th class='sch4'>RAJSHREE 10 A</th><th class='sch5'>S.LAXMI 20 A</th></tr>",
    "<tr><td class='tdw'>",
    "retspan",
    "bdres_proc.asp",
    "resdate",
    "indate=",
    "fromdate",
    "todate",
    "<table align='center' width='40%'  border=2 bgcolor='#003366' bordercolor=white cellpadding=5>",
    "<tr><td align='right' width='60%'>Play Point: </td><td align='right' width='40%'>",
    "toFixed",
    "</td></tr><tr><td align='right' width='60%'>Cancelled Point: </td><td align='right' width='40%'>",
    "</td></tr><tr><td align='right' width='60%'>Win Point: </td><td align='right' width='40%'>",
    "</td></tr><tr><td align='right' width='60%'>Net: </td><td align='right' width='40%'>",
    "reportspan",
    "report_proc.asp",
    "fromdate=",
    "&todate=",
    "From Date Cannot Be Greater Than To Date.....",
    "oldpass",
    "newpass",
    "Password Changed Successfully..",
    "Oops Problem in Password Change..",
    "cp_proc.asp",
    "oldpass=",
    "&newpass=",
    ":",
    " ",
    "PM",
    "pm",
    ":0",
    "currtime",
    "Current Time : ",
    "<br>",
    "counter9",
    "logoutdiv",
    "welcomediv",
    "logindiv",
    "login_proc.asp",
    "uname=",
    "username",
    "&passwd=",
    "passwd",
    "N",
    "className",
    "tbmppink",
    "substr",
    "toString",
    "num",
    "padStart",
    "tbmpyel",
    "tbmp",
    "tball",
    "focus",
    "tbh",
    "tbv",
    "keyCode",
    "tbh9",
    "tbh0",
    "tbv9",
    "tbv0",
    "-",
    "slice",
    "rga",
    "rgb",
    "rgc",
    "rra",
    "rsa",
    "currres_proc.asp",
    "L",
    "Checked",
    "h",
    "shres",
    "Hide Results",
    "Q",
    "Show Results",
    "checked",
    "s",
    "s0",
    "sall",
    "seven",
    "sodd",
    "lbl",
    "lblleft0",
    "000-",
    "099",
    "lblleft1",
    "100-",
    "199",
    "lblleft2",
    "200-",
    "299",
    "lblleft3",
    "300-",
    "399",
    "lblleft4",
    "400-",
    "499",
    "lblleft5",
    "500-",
    "599",
    "lblleft6",
    "600-",
    "699",
    "lblleft7",
    "700-",
    "799",
    "lblleft8",
    "800-",
    "899",
    "lblleft9",
    "900-",
    "999",
    "0,1,2,3,4,5,6,7,8,9",
    "0,2,4,6,8",
    "1,3,5,7,9",
    "tdg",
    "tdgw",
    "lblleft",
    "2",
    "cballlow",
    "cblow0",
    "cblow1",
    "cblow2",
    "cblow3",
    "cblow4",
    "cblow5",
    "cblow6",
    "cblow7",
    "cblow8",
    "cblow9",
    "cbhigh0",
    "cbhigh1",
    "cbhigh2",
    "cbhigh3",
    "cbhigh4",
    "cbhigh5",
    "cbhigh6",
    "cbhigh7",
    "cbhigh8",
    "cbhigh9",
    "cbeven",
    "cbodd",
    "cball",
    "cbhigh",
    "tdg0",
    "tdg1",
    "tdg2",
    "tdg3",
    "tdg4",
    "tdg5",
    "tdg6",
    "tdg7",
    "tdg8",
    "tdg9",
    "cblow",
    "rbmul1",
    "rbmul2",
    "rbmul5",
    "rbmul10",
    "rbmul20",
    "(Rs.   2 )",
    "(Rs.   4 )",
    "(Rs.   10 )",
    "(Rs.   20 )",
    "(Rs.   40 )",
    "lbllow0",
    "lbllow1",
    "lbllow2",
    "lbllow3",
    "lbllow4",
    "lbllow5",
    "lbllow6",
    "lbllow7",
    "lbllow8",
    "lbllow9",
    "tbqa",
    "tbqb",
    "tbqc",
    "tbqd",
    "tbqe",
    "tbqf",
    "tbqg",
    "tbqh",
    "tbqi",
    "tbqj",
    "tbaa",
    "tbab",
    "tbac",
    "tbad",
    "tbae",
    "tbaf",
    "tbag",
    "tbah",
    "tbai",
    "tbaj",
    "cbfp",
    "tblcamt",
    "tblcqty",
    "Text",
    "H",
    "txtLuckyStone",
    "Lucky Pick Blank!",
    "random",
    "floor",
    "indexOf",
    "push",
    "Please Enter Value Less Than 100!",
    "<table width='100%' border='0' height=400 bgcolor=#ffffc0><tr><td align=center><table width='80%'>",
    '<tr><td colspan=4 class="tdorange"><input type="checkbox" id="cballad" value="0" onclick="alladv();">ALL</td><td class="tdorange"><label onclick="closeadv();">Close</label></td></tr>',
    "<tr>",
    "</tr><tr>",
    '<td class="tdorange"><input type="checkbox" id="sd',
    '" value="',
    '" onclick="perdraw();">&nbsp;',
    "</td>",
    "</tr>",
    "<tr><td colspan=5>Advance Draws Not Available..</td></tr>",
    "</table></td></tr></table>",
    "cballad",
    "sd",
    "OOPS!..MINIMUM BET POINTS 10 ....",
    "OOPS!...BETS ARE BLANK ....",
];
//print_r($_33bf);
?>
function showhide(L, H) {
    if (L == <?=$_33bf[222]?>) {
        if (H == <?=$_33bf[222]?>) {
            document[<?= $_33bf[10]?>](<?= $_33bf[16]?>)[<?= $_33bf[15]?>][<?= $_33bf[14]?>] = <?= $_33bf[17]?>];
            document[<?=$_33bf[10]?>](<?=$_33bf[18]?>)[<?= $_33bf[15]?>][<?=$_33bf[14]?>] = <?=$_33bf[19]?>;
            highlowstatus = <?=$_33bf[8]?>;
            clearbets();
            leftset(0);
            mulfunc(1);
            cballlow[<?=$_33bf[223]?>] = false;
        } else {
            document[<?=$_33bf[10]?>](<?=$_33bf[16]?>)[<?=$_33bf[15]?>][<?=$_33bf[14]?>] = <?=$_33bf[19]?>;
            document[<?=$_33bf[10]?>](<?=$_33bf[18]?>)[<?=$_33bf[15]?>][<?=$_33bf[14]?>] = <?=$_33bf[17]?>;
            highlowstatus = <?=$_33bf[224]?>;
            clearbets();
            leftset(0);
            mulfunc(1);
            cballlow[<?=$_33bf[223]?>] = false;
        }
    } else {
        if (L == <?=$_33bf[5]?>) {
            if (rpflag == <?=$_33bf[5]?>) {
                document[<?=$_33bf[10]?>](<?=$_33bf[20]?>)[<?=$_33bf[15]?>][<?=$_33bf[14]?>] = <?=$_33bf[19]?>;
                document[<?=$_33bf[10]?>](<?=$_33bf[21]?>)[<?=$_33bf[15]?>][<?=$_33bf[14]?>] = <?=$_33bf[17]?>;
                document[<?=$_33bf[10]?>](<?=$_33bf[225]?>)[<?=$_33bf[35]?>] = <?=$_33bf[226]?>;
                rpflag = <?=$_33bf[227]?>;
            } else {
                if (rpflag == <?=$_33bf[227]?>) {
                    document[<?=$_33bf[10]?>](<?=$_33bf[20]?>)[<?=$_33bf[15]?>][<?=$_33bf[14]?>] = <?=$_33bf[17]?>;
                    document[<?=$_33bf[10]?>](<?=$_33bf[21]?>)[<?=$_33bf[15]?>][<?=$_33bf[14]?>] = <?=$_33bf[19]?>;
                    document[<?=$_33bf[10]?>](<?=$_33bf[225]?>)[<?=$_33bf[35]?>] = <?=$_33bf[228]?>;
                    rpflag = <?=$_33bf[5]?>;
                }
            }
        }
    }
}